  <nav class="navbar">
    <div class="container-fluid">
      <a class="navbar-brand" href="#"><img width="300" height="50" src="https://zummer.su/wp-content/uploads/2017/12/zummer-logo.png" alt="" srcset=""></a>
      <div class="d-flex">
        <form action="/users/list" method="get">
          <button class="btn" type="submit">Учётные записи</button>
        </form>
        <form action="/account/logout" method="post">
          <button class="btn logout" type="submit">Выйти из аккаунта</button>
        </form>
      </div>
    </div>
  </nav>
  <div class="container">
  </div>
  <?= $this->getContent();?>