<div class="container update position-absolute top-50 start-50 translate-middle login">
    <form method="post">
        <div class="container text-center">
            <span class="formheader">Изменение данных пользователя</span>
        </div>
        <div class="row row-cols-1 mt-4">
            <div class="col mb-3 ">
                <label for="name" class="form-label">Имя</label>
                <input type="text" class="form-control" id="name" name="name" value="<?php echo $user['name'] ?>">
                <small><?php if (isset($errors['name'])) :
                            echo $errors['name']; ?> <style>
                            #name {
                                border-color: red;
                            }
                        </style>
                    <?php endif; ?> </small>
            </div>
        </div>
        <div class="row">
            <div class="col mb-3">
                <label for="email" class="form-label">Почта</label>
                <input type="email" class="form-control" id="email" name="email" value=<?php echo $user['email'] ?>>
                <small><?php if (isset($errors['email'])) :
                            echo $errors['email']; ?> <style>
                            #email {
                                border-color: red;
                            }
                        </style>
                    <?php endif; ?> </small>
            <div class="row mt-4">
                <div class="col mb-3">
                    <p>Текущая роль: <?php echo $user['role'] ?></p>
                    <label for="role" class="form-label">Выбрать новую роль: </label>
                    <select name="role" id="role">
                        <option value=<?php echo $user['role'] ?>>Список ролей: </option>
                        <option value="admin">Администратор</option>
                        <option value="client">Клиент</option>
                        <option value="employee">Сотрудник</option>
                        <option value="guest">Гость</option>
                    </select>
                </div>
            </div>
            <button type="submit" class="container text-center btn btn-primary mb-3">Изменить</button>
    </form>
</div>