<div class="m-3">
    <div class="row">
        <div class="col-md-3">
            <div class="card">
                <div class="card-header">
                    <h5 class="card-title">Роли</h5>
                    <h5 class="card-title role" style="display: none;"></h5>
                </div>
                <ul class="list-group list-group-flush" id="rolesList">
                    <?php $iter = 0;
                    foreach ($roles_desc as $role) { ?>
                        <li class="list-group-item" value="<?= $roles[$iter] ?>"><?= $role ?></li>
                    <?php $iter++;
                    }  ?>
                </ul>
            </div>
            <div class="button-actions mt-3">
                <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#addRolesModal" data-bs-whatever="addRolesModal">
                    Добавление роли
                </button>
                <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#delRolesModal" data-bs-whatever="delRolesModal">
                    Удаление роли
                </button><br>
                <button class="btn btn-primary mt-3" id="send" type="button">Подтвердить</button>
            </div>
        </div>
        <div class="col-md-9" id="controllersList" style="display: none;">
            <div class="row row-cols-3">
                <?php $iter = 0;
                foreach (json_decode($controllers) as $controller => $actions) {
                ?>
                    <div class="col">
                        <div class="card mb-3">
                            <div class="card-header">
                                <h5 class="card-title"><?= $controllers_desc[$iter] . "($controller)" ?></h5>
                            </div>
                            <ul class="list-group list-group-flush">
                                <?php foreach ($actions as $action) { ?>
                                    <li class="list-group-item">
                                        <label for="<?= $action ?>"><?= $action ?></label>
                                        <input class="allowList" id="<?= $action ?>" type="checkbox" name="<?= $controller ?>" value="<?= $action ?>">
                                    </li>
                                <?php } ?>
                            </ul>
                        </div>
                    </div>
                <?php $iter = $iter + 1;
                } ?>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="addRolesModal" tabindex="-1" aria-labelledby="addRolesModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="addRolesModalLabel">Добавление роли</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <form method="post">
                <div class="modal-body">
                    <div class="mb-3 add-role">
                        <label for="role-name" class="col-form-label">Код роли</label>
                        <input type="text" class="form-control" name="role">
                    </div>
                    <div class="mb-3 add-role">
                        <label for="role-desc-name" class="col-form-label">Название роли</label>
                        <input type="text" class="form-control" name="role_desc">
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Закрыть</button>
                    <button type="submit" class="btn btn-primary add">Сохранить</button>
                </div>
            </form>
        </div>
    </div>
</div>
<div class="modal fade" id="delRolesModal" tabindex="-1" aria-labelledby="delRolesModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="delRolesModalLabel">Удаление роли</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <form method="post">
                <div class="modal-body">
                    <div class="mb-3 del-role">
                        <h5>Выберите роль для удаления:</h1>
                            <ol class="list-group list-group-flush list-group-numbered">
                                <?php $iter = 0;
                                foreach ($roles_desc as $role) { ?>
                                    <li class="list-group-item rolesList">
                                        <label for="<?= $roles[$iter] ?>"><?= $role ?></label>
                                        <input type="checkbox" id="<?= $roles[$iter] ?>" name="<?= $roles[$iter] ?>">
                                    </li>
                                <?php $iter++;
                                }  ?>
                            </ol>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Закрыть</button>
                    <button type="submit" class="btn btn-primary del">Сохранить</button>
                </div>
            </form>
        </div>
    </div>
</div>
<script>
    document.addEventListener('DOMContentLoaded', function() {
        const rolesList = document.getElementById('rolesList');
        const controllersList = document.getElementById('controllerList');
        const allowList = document.querySelectorAll('.allowList');
        const allowData = <?php echo $allow_list ?>;
        let dataToSend = <?php echo $allow_list ?>;
        let role;
        let conditionData = {};


        function getCurrentRole() {
            const currentRole = document.querySelector('.role');
            currentRole.textContent = `Текущая роль: ${event.target.textContent}`
            currentRole.style.display = 'block';
        }
        rolesList.addEventListener('click', function() {
            role = event.target.getAttribute('value');
            getCurrentRole();
            addCheckedList(role);
            console.log(role);
        })

        allowList.forEach(function(input) {
            input.addEventListener('click', function() {
                const setCheck = event.target.checked;
                const action = event.target.getAttribute('value');
                const controller = event.target.getAttribute('name');

                console.log(setCheck);
                console.log(action);
                console.log(controller);
                console.log(role);
                if (!conditionData[role]) {
                    conditionData[role] = {};
                }
                if (!conditionData[role][controller]) {
                    conditionData[role][controller] = {};
                }
                conditionData[role][controller][action] = setCheck;
                dataToSend[role][controller][action] = setCheck;
                console.log(conditionData);
            });
        });

        function addCheckedList(role) {
            console.log(conditionData);
            const controllers = allowData[role];
            for (const controller in controllers) {
                const actions = controllers[controller];
                for (const action in actions) {
                    const allow = actions[action];
                    const input = document.querySelector(`input[name="${controller}"][value="${action}"]`)
                    if (allow) {
                        input.checked = true;

                    } else {
                        input.checked = false;

                    }
                }
            }
            if (conditionData[role]) {
                const conditionControllers = conditionData[role];
                for (const controller in conditionControllers) {
                    const actions = conditionControllers[controller];
                    for (const action in actions) {
                        const allow = actions[action];
                        const input = document.querySelector(`input[name="${controller}"][value="${action}"]`)
                        if (allow) {
                            input.checked = true;
                        } else {
                            input.checked = false;
                        }
                    }
                }

            }

            document.getElementById('controllersList').style.display = 'block';
            console.log(dataToSend);
        }

        const delbtnModal = document.querySelector('[data-bs-whatever="delRolesModal"]');
        const ol = document.querySelector('.list-group-numbered');
        const fol = document.querySelectorAll('ol input');
        const delbtn = document.querySelector('.del');
        let rolesDataToSend = [];

        ol.addEventListener('click', function(event) {
            if (event.target.closest('.rolesList')) {
                const input = event.target.querySelector('input');
                input.checked = !input.checked;

            }
            console.log(ol);
            console.log(event.target.closest('.rolesList'));
            console.log(event.target.querySelector('input'));
        });

        const btn = document.getElementById("send");
        btn.addEventListener('click', function() {
            fetch('/access/', {
                    method: "POST",
                    headers: {
                        "Content-Type": "application/json",
                    },
                    body: JSON.stringify(dataToSend),
                })
                .then((response) => {
                    location.replace('/access');
                    return response.json();
                })

        });
    });
</script>