<div class="m-3">
    <div class="row">
        <div class="col-md-3">
            <div class="card">
                <div class="card-header">
                    <h5 class="card-title">Роли</h5>
                </div>
                <ul class="list-group list-group-flush" id="rolesList">
                    <?php $iter = 0;
                    foreach ($roles_desc as $role) { ?>
                        <li class="list-group-item" value="<?= $roles[$iter] ?>"><?= $role ?></li>
                    <?php $iter++;
                    }  ?>
                </ul>
            </div>
            <form method="get">
                <button class="btn btn-primary mt-3" type="submit">Добавить роль</button>
                <button class="btn btn-primary mt-3" type="submit">Удалить роль</button><br>
            </form>
            <button class="btn btn-primary mt-3" type="submit">Подтвердить</button>
        </div>
        <div class="col-md-9" id="controllersList" style="display: none;">
            <div class="row row-cols-3">
                <!-- Здесь добавляются карты контроллеров !-->
                <div class="col">
                    <div class="card mb-3">
                        <div class="card-header">
                            <h5 class="card-title">Добавить сюда название контроллера</h5>
                        </div>
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item">
                                <label for="access">
                                    xui
                                    <input class="allowList" type="checkbox">
                                </label>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
<script>
    document.addEventListener('DOMContentLoaded', function() {
        const controllersList = document.getElementById('controllerList');

        const allowList = document.querySelectorAll('.allowList');
        const allowData = <?php echo $allow_list ?>;
        const controllersData = <?php echo $controllers ?>;
        rolesList.addEventListener('click', function() {
            const role = event.target.getAttribute('value');
            addControllerCard();
            document.getElementById('controllersList').style.display = 'block';
            addControllers(role);
            console.log(role);
        })

        function addControllerCard() {
            const controllers = Object.keys(controllersData);
            const controllerCard = document.querySelector('.row.row-cols-3');
            const card = controllerCard.querySelector('.col');
            for (let index = 0; index < controllers.length-1; index++) {
                const copiedCard = card.cloneNode(true);
                controllerCard.appendChild(copiedCard);
            }
        }

        function addControllers(role) {
            const controllers = allowData[role];
            for (const controller in controllers) {
                const actions = controllers[controller];
                for (const action in actions) {
                    const allow = actions[action];
                    if (allow) {
                        const input = document.querySelector(`input[name="${controller}"][value="${action}"]`)
                        input.checked = true;
                    }
                }
            }
            document.getElementById('controllersList').style.display = 'block';
        }

        function addActions() {
            const role = event.target.textContent.trim(); // Получаем текст роли
            const controller = event.target.textContent;
            // Очищаем список контроллеров
            actionsList.innerHTML = '';
            console.log(Object.values(controller));
            // Заполняем список контроллеров

            for (let action of controllersData[controller]) {
                const li = document.createElement('li');
                li.classList.add('list-group-item'); // Добавляем класс "list-group-item"
                li.textContent = action;
                actionsList.appendChild(li);
                const input = document.createElement('input');
                input.setAttribute('type', 'text'); // Устанавливаем тип поля ввода
                input.setAttribute('value', action); // Устанавливаем значение поля ввода
                input.classList.add('form-control'); // Добавляем класс Bootstrap для стилизации
                actionsList.appendChild(input);

            }
            document.getElementById('actions').style.display = 'block';
        }
    });
</script>