<style>
    body {
        display: flex;
        align-items: center;
        justify-content: center;
        height: 100vh;
        margin: 0;
    }

    .error-container {
        text-align: center;
    }
</style>
<div class="error-container">
    <h1>403 Forbidden</h1>
    <p>У вас нет доступа к запрашиваемому ресурсу. Вы будете перенаправлены на главную страницу через 3 секунды</p>
</div>
<script>

</script>