<style>
    body {
        display: flex;
        align-items: center;
        justify-content: center;
        height: 100vh;
        margin: 0;
    }

    .error-container {
        text-align: center;
    }
</style>
<div class="error-container">
    <h1>Страницы не существует</h1>
    <p>Вы можете перейти на <a href="/">главную страницу</a> или <a href="/info/">связаться с нами</a></p>
</div>
<script>

</script>