<style>
    body {
        display: flex;
        align-items: center;
        justify-content: center;
        height: 100vh;
        margin: 0;
    }

    .error-container {
        text-align: center;
    }
</style>
<div class="error-container">
    <h1>Доступ запрещён</h1>
    <p>У вас нет доступа к запрашиваемому ресурсу так как вы не вошли в учётную запись</p>
    <p> Перейдите по ссылке для входа в учётную запись <a href="/account/login">Вход в аккаунт</a></p>
    <p>Также вы можете перейти на <a href="/">главную страницу</a> или <a href="/info/">связаться с нами</a></p>
</div>
<script>

</script>