<div class="position-absolute top-50 start-50 translate-middle"><?php echo $this->getContent();?>
    <div class="container">
        <style>
            .container {
                border-radius: 30px;
                padding: 30px;
                box-shadow: -2px 2px 73px -22px #060607;
                max-width: 350px;
            }
        </style>
        <div class="container_title text-center mb-4">
            <h5>Создание нового пароля</h5>
        </div>
        <form method="post">
            <label for="inputPassword" class="form-label">Новый пароль:</label>
            <input type="password" id="inputPassword" class="form-control" aria-describedby="passwordHelpBlock" name="password">
            <?php if (isset($errors) && !empty($errors)):?><small><?php echo $errors;?></small><?php endif; ?>
            <div id="passwordHelpBlock" class="form-text mb-4">
                Ваш пароль должен состоять из 8–20 символов, содержать буквы и цифры и не должен содержать пробелов, специальных символов или смайлов.
            </div>
            <label for="inputPasswordConfirm" class="form-label">Подтверждение нового пароля:</label>
            <input type="password" id="inputPasswordConfirm" class="form-control" name="password-confirm">
            <?php if (isset($errors) && !empty($errors)):?><small><?php echo $errors;?></small><?php endif; ?>
            <div class="text-center mt-4">
                <button class="btn btn-primary" type="submit">Подтвердить</button>
            </div>
        </form>
    </div>
</div>
