 <div class="container position-absolute top-50 start-50 translate-middle login">
     <form method="post">
         <div class="container text-center">
             <span class="formheader">Восстановление доступа</span>
         </div>

         <div class="mb-3 mt-4">
             <label for="resovery" class="form-label">Введите почту</label>
             <input type="email" class="form-control" id="email" name="email">
         </div>
         <button type="submit" class="container text-center btn btn-primary mb-3 mt-2">Восстановить</button>
 </div>